dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh | bash
notification:
  slack:
    room:  
      secure: "Xl/5ykF0iCoToOECI9Z8jrheGx3wIIXELWywim+uU3hFE5KmY9QnCLqiGxhNlejtohG2d7TVGNjNpEV+ooXtx7FXulvS3TMMZLsI3GC9HPr7FhFORzaKa+/RbbJv7nZ56K1JkGq2vBSe9JuTB+yoHqtYiOnTDYCq7VHxIYMRgVs+Vjj1zWlH1FdJcyR3+TNchNkfykpckH820CVIyOKB1ckoQMyKNAGpDVnoyLGeXaGQJ/r5hs22b2Nyw8ot9a03oDLq+csy8vbyFmbezXrkM2j7zrmuqFz5GTG16QUBSh0GqJGTYanLDGKLWBzEi8fnz347eV2QC05dcb4/zYum3taO9davs/FMEm9xzhHGO0puEQUwl2odoHh0u52hjV0iZq+jbAlDXI6oENeI0i1huwL52HKYQfJ8cn5LKsft7sszsxUj45lnJ6LNYtzoKA+msWFHiW2RH9SNZb3dpJcQL25O4/VWbhtnI9m1d20P2+uupNprchUAGsl6BqjnLThzKSxcD6Xu5pD8SP/xaTgmWkVT/sMVCds1aQSER1WttRppF48iOx6HfteKUPngq8lvyxK5rdg1em5XQFKn5KR3pfjnvMhAN9Y665HJAcsTCTQDrhLz+7ed7TvhmrLCxLFi/iQTUpg9kUuG4XBw+nFm2qVzduNwV8YWs3bDnwraOCo="
